name: Daily Fork Update

on:
  push:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 00:00 触发，可根据需求调整触发时间

jobs:
  update_fork:
    name: Update Fork and Commit Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "chunjinchen"
          git config user.email "chunjinchen1998@gmail.com"

      - name: Fetch Upstream Changes
        run: |
          git fetch origin
          git checkout master 
          git remote add upstream https://github.com/ACL4SSR/ACL4SSR.git
          git fetch upstream
          git switch -c convert origin/master
          git merge upstream/master --no-edit --no-stat -v

      - name: Start Convert
        run: |
          pushd ./Clash/config || return 1
          # 使用find命令递归查找当前目录及其子目录下的所有文件，但排除.sh和.md文件
          find . -type f -not -name '*.sh' -not -path './.*/*' -not -name '*.md' -print0 | while IFS= read -r -d '' file; do
            # 使用sed命令进行替换，并将结果写回原文件
            sed -i 's|https://raw\.githubusercontent\.com/ACL4SSR/ACL4SSR/master|https://cdn\.jsdelivr\.net/gh/chunjinchen/ACL4SSR@master|g' "$file"
           echo "替换完成: $file"
          done

      - name: Commit Changes
        run: |
          git add .  
          git commit -m "Daily update: $(date +'%Y-%m-%d')"
          git switch master
          git rebase convert
          git push origin master  
